### PR TITLE
Web url param patch

### PR DESCRIPTION
**Pull request by jihoonl**
utilise urllib.urlencode module

Use eval function in javascript to parse this.

view-source:http://chimek.yujinrobot.com/rosjs/listener.html

### CODE REVIEW

**Comment by jihoonl** [comment]
The pull request is not the ultimate solution to fix all the problems. But it shows that utilizing eval() function in javascript helps to solve the problem we faced.

**Comment by stonier** [comment]
What is the eval() function? I must have missed that.

Don't mind me - didn't read your initial post properly.

**Comment by jihoonl** [comment]
eval() is a conversion function from string to actual code representation.

For example, 

eval('call_back_func()'); is equal to call_back_func();

**Comment by stonier** [comment]
Tackled this a bit differently and it should get us the ultimate solution. Comments in the code below. What is important is for us to get the parameters (yaml string) and remappings (list of rocon_std_msgs.Remapping) objects converted into the proper python objects before converting into json.

Should all be hunky dory now.

```
    def _get_webapp_url(self, app):
        """
           url syntheiser for sending remappings and parameters information.
           We convert the interaction parameter (yaml string) and remapping (rocon_std_msgs.Remapping[])
           variables into generic python list/dictionary objects and convert these into
           json strings as it makes it easier for web apps to handle them.
        """
        url = app['name']
        json_args = {}
        # The parameters variable is a yaml string:
        #  - convert this to a python object
        #  - convert to a json string
        #  - url encode the symbols
        yaml_string = app['parameters']
        if yaml_string:
            json_string = json.dumps(yaml.load(yaml_string))
            rospy.logwarn("Json string: %s" % json_string)
            json_args['params'] = json_string
        # The remappings variable is a bit more complicated
        #  - convert rocon_std_msgs.Remapping[] to list of dics in the form of [ { remap_from: 'xyz', remap_to: 'zyx' } ]
        #  - convert to a json string
        #  - url encode the symbols
        remappings = []  # need to create a list of dictionaries (note: app['remappings'] is a list of rocon_std_msgs.Remapping)
        if len(app['remappings']) != 0:
            for r in app['remappings']:
                remapping = {}
                remapping['remap_from'] = r.remap_from
                remapping['remap_to'] = r.remap_to
                remappings.append(remapping)
            json_string = json.dumps(remappings)
            json_args['remaps'] = json_string
        url += "?" + urllib.urlencode(json_args)
        return url
```

**Comment by stonier** [comment]
The interactions format must look like the following:

```
  parameters: "{rosbridge_address: '%ROSBRIDGE_ADDRESS%', rosbridge_port: %ROSBRIDGE_PORT%}"
  remappings:
    - remap_from: chatter
      remap_to: babbler
```

**Comment by stonier** [comment]
Not merging this - c377624d43b3fa2abf2a85e8fb91572408e8c446 fixes it and also does the remappings properly.

Thanks for the heads up on urlencode though!

**Comment by jihoonl** [comment]
How about this. It there any reason that only parameter is passed as string?
`
  parameters: 
      -rosbridge_address: '%ROSBRIDGE_ADDRESS%'
      -rosbridge_port: '%ROSBRIDGE_PORT%'
  remappings:
    - remap_from: chatter
      remap_to: babbler
`

**Comment by stonier** [comment]
Yeah. I wanted to do that also. But the parameters are unknown and they need to go into a ros msg. So that was the reason it was left as a yaml string (the Interaction.parameter variable is a string). 

However. We could input it like you have and then the interactions manager converts the parameter dic into a yaml string for the ros message.

This is a good idea. Thanks for bumping it and making me think again.

**Comment by stonier** [comment]
Implemented that idea in https://github.com/robotics-in-concert/rocon_tools/commit/8e591d93f50b2696f0d42ce67bac4bca0fc64d1b . It doesn't require to be constrained to a list of key-value pairs. Freeform yaml is fine.

**Pull request closed without merging**
