### PR TITLE
Implementation or rqt remocon

### PR DESCRIPTION
**Pull request by dwlee**
- Separate previous interactions chooser into role chooser class and interactions chooser.
- Delete and simplify unused arguments(ex. concert name, master index, so on).
- Update rqt remocon.

### CODE REVIEW

**Comment by jihoonl** [comment]
Tried with chirp.
log

**Comment by dwlee** [comment]
Update way of interactions status update to remove qt warning message.

**Comment by jihoonl** [comment]
It gets RuntimeError

```
^[[Ajihoonl@whoola:~/research/ros/rocon/src/rocon_qt_gui/rocon_remocon$ rqt_remocon 
You are terminator, an esoteric and unsupported terminal
 --> falling back to 'gnome-terminal'
[debug] Interactive Client : initialised
[debug] Interactive Client : Connection Details
[debug] Interactive Client :   Node Name: rqt_remocon_3f9a275ba97f45c9a4269a1a9c30bce2
[debug] Interactive Client :   ROS_MASTER_URI: http://192.168.10.166:11311
[debug] Interactive Client :   ROS_HOSTNAME: 192.168.10.129
[debug] Interactive Client :   ROS_MASTER_PORT: 11311
[debug] Interactive Client : Get interactions service Handle
[debug] Interactive Client : publishing remocon status
[debug] Interactive Client : pairing status callback [][]
[debug] init QInteractionsChooser
[debug] Role Chooser : switching to the interactions list
[debug] InteractiveClientUI : switching to the interactions list
[debug] Interactions Chooser : refreshing the interactions list
[debug] Interactions Chooser : disabling stop interactions button [Make A Map]
[debug] Interactions Chooser : disabling stop interactions button [Keyboard Teleop]
[debug] Interactions Chooser : disabling stop interactions button [Chirp]
[debug] Interactions Chooser : starting interaction []
[debug] Interactive Client : interaction request granted
[debug] Interactive Client : start a dummy interaction for triggering a pair
[info] InteractiveClientInterface : starting paired dummy interaction
[debug] Interactive Client : publishing remocon status
[debug] Interactions Chooser : refreshing the interactions list
[debug] Interactive Client : pairing status callback [rocon_apps/chirp][rqt_remocon_3f9a275ba97f45c9a4269a1a9c30bce2]
[debug] Interactive Client : pairing status callback [][rqt_remocon_3f9a275ba97f45c9a4269a1a9c30bce2]
[debug] Interactive Client : the rapp in this paired interaction terminated
[info] Interactive Client : interaction stopped [_365a83fb096c4acfa340a4f2f5cdf387]
[debug] Interactive Client : publishing remocon status
[debug] InteractiveClientUI : interactions_updated_relay
[debug] Interactions Chooser : refreshing the interactions list
[debug] Interactive Client : pairing status callback [][]
[debug] Interactions Chooser : disabling stop interactions button [Make A Map]
[debug] Interactions Chooser : starting interaction [turtlebot_rviz_launchers/view_teleop_navigation.launch]
[debug] Interactive Client : interaction request granted
[debug] Interactive Client : pairing status callback [turtlebot_rapps/make_a_map][rqt_remocon_3f9a275ba97f45c9a4269a1a9c30bce2]
[debug] Interactive Client : roslaunchable [turtlebot_rviz_launchers/view_teleop_navigation.launch]
[debug] Interactive Client : publishing remocon status
[debug] Interactions Chooser : refreshing the interactions list

(gnome-terminal:12314): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
[debug] Interactions Chooser : enabling stop interactions button [Make A Map]
[debug] Interactions Chooser : stopping interaction turtlebot_rviz_launchers/view_teleop_navigation.launch 
Terminating roslaunch [pid: 12324]
[debug]   unlinking /tmp/tmp2jJZiI
[info] Interactive Client : interaction stopped [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[debug] Interactive Client : publishing remocon status
[debug] Interactions Chooser : refreshing the interactions list
[debug] Interactions Chooser : disabling stop interactions button [Make A Map]
[debug] Interactive Client : process_listener detected terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[warning] Interactive Client : process_listener detected unknown terminating interaction [make_a_map_211a52a61fe84210a32e7661fef0e0e7]
[debug] Interactions Chooser : disabling stop interactions button [Chirp]
[debug] Interactions Chooser : starting interaction []
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/interactions_chooser.py", line 139, in _start_interaction
    QMessageBox.warning(self, 'Start Interaction Failed', "%s." % message.capitalize(), QMessageBox.Ok)
RuntimeError: super-class __init__() of type QInteractionsChooser was never called
[debug] Interactions Chooser : disabling stop interactions button [Chirp]
[debug] Interactions Chooser : disabling stop interactions button [Chirp]
[debug] Interactions Chooser : starting interaction []
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/interactions_chooser.py", line 139, in _start_interaction
    QMessageBox.warning(self, 'Start Interaction Failed', "%s." % message.capitalize(), QMessageBox.Ok)
RuntimeError: super-class __init__() of type QInteractionsChooser was never called
[debug] Interactions Chooser : disabling stop interactions button [Chirp]
[debug] Interactions Chooser : disabling stop interactions button [Chirp]
[debug] Interactions Chooser : starting interaction []
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/interactions_chooser.py", line 139, in _start_interaction
    QMessageBox.warning(self, 'Start Interaction Failed', "%s." % message.capitalize(), QMessageBox.Ok)
RuntimeError: super-class __init__() of type QInteractionsChooser was never called
[debug] Interactions Chooser : disabling stop interactions button [Chirp]
[debug] Interactive Client : pairing status callback [][]
[debug] Interactive Client : pairing status callback [][]
```

**Comment by jihoonl** [comment]
:+1:

**Pull request merged**
