### PR TITLE
Interactions overhaul

### PR DESCRIPTION
**Pull request by stonier**
Mostly about getting interactions free from the concert.
- Updates from the `rocon_utilities` fallout
- Depracated 'has_keys' functions replaced
- `rocon_remocon` de-concertified
- lots of pep8 updates
- `rocon_remocon` checker simplified
- `rocon_remocon` now uses the rospkg home function
- `rocon_remocon` now tables all apps according to unique hash, not the non-unique name.

Brought to you by https://github.com/robotics-in-concert/rocon_concert/issues/188

### CODE REVIEW

**Comment by jihoonl** [comment]
concert_conductor_graph is broken

```
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/concert_conductor_graph/src/concert_conductor_graph/conductor_graph.py", line 293, in _update_conductor_graph
    self._refresh_rosgraph()
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/concert_conductor_graph/src/concert_conductor_graph/conductor_graph.py", line 299, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/concert_conductor_graph/src/concert_conductor_graph/conductor_graph.py", line 304, in _generate_dotcode
    orientation='LR'
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/concert_conductor_graph/src/concert_conductor_graph/dotcode.py", line 284, in generate_dotcode
    simplify=simplify,
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/concert_conductor_graph/src/concert_conductor_graph/dotcode.py", line 237, in generate_dotgraph
    self._add_node(n, rosgraphinst=rosgraphinst, dotcode_factory=dotcode_factory, dotgraph=dotgraph)
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/concert_conductor_graph/src/concert_conductor_graph/dotcode.py", line 69, in _add_node
    url=rocon_utilities.gateway_basename(node),
AttributeError: 'module' object has no attribute 'gateway_basename'
```

**Comment by stonier** [comment]
> concert_conductor_graph is broken

Are you sure you are using the right branch? There is no rocon_utilities reference in concert_conductor_graph on indigo branch:

https://github.com/robotics-in-concert/rocon_qt_gui/blob/indigo/concert_conductor_graph/src/concert_conductor_graph/dotcode.py

**Comment by jihoonl** [comment]
I tried to rerun the code with precleaned compliation. and got an error below. Different from above.

```
RosPluginProvider.load(concert_conductor_graph/Conductor Graph) exception raised in __builtin__.__import__(concert_conductor_graph.conductor_graph, [ConductorGraph]):
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 77, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/home/jihoonl/research/ros/rocon/src/rocon_qt_gui/concert_conductor_graph/src/concert_conductor_graph/conductor_graph.py", line 13, in <module>
    from python_qt_binding import Signal
ImportError: cannot import name Signal

PluginManager._load_plugin() could not load plugin "concert_conductor_graph/Conductor Graph":
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 98, in load
    self._load()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 83, in load
    raise e
ImportError: cannot import name Signal
```

**Comment by stonier** [comment]
Ok...looks like there might be a problem. I can't fix them on this computer unfortunately.

**Comment by stonier** [comment]
@dwlee bump.

**Pull request merged**
