### PR TITLE
Added rocon_remocon application icon and bugfix set_node_color for gate and conductor graphs. 

### PR DESCRIPTION
**Pull request by kentsommer**
Gave rocon_remocon an application icon to display in the tray similar to how rqt has its own icon. 
#133

### CODE REVIEW

**Comment by kentsommer** [comment]
This currently uses the rocon_logo for the icon but can be changed to something else if wanted.

**Comment by jihoonl** [comment]
:100:

**Comment by jihoonl** [comment]
Can we use rocon_icon package instead of adding extra image on rocon_remocon package?
All Icons we used in rocon can be found [here](https://github.com/robotics-in-concert/rocon_tools/tree/hydro-devel/rocon_icons/icons)

**Comment by stonier** [comment]
+1 to that. The icons here I see are getting loaded from rospack, so you could just as easily get straight from rocon_icons.

@kentsommer, can you make that change?

**Comment by kentsommer** [comment]
@stonier change has been made to use rocon_icons package instead in 99d6d4bd66bfd1b6621040221d32adf80f095638

**Comment by stonier** [comment]
Awesome! :neckbeard:

**Pull request merged**
